#!/bin/sh

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

if [ "$(basename "$SCRIPT_DIR")" = "deploy" ]; then
  DEPLOY_DIR=$SCRIPT_DIR
  REPO_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
else
  REPO_DIR=$SCRIPT_DIR
  DEPLOY_DIR=$REPO_DIR/deploy
fi

ENV_FILE=$DEPLOY_DIR/.env
ENV_EXAMPLE_FILE=$DEPLOY_DIR/.env.example
COMPOSE_FILE=$DEPLOY_DIR/docker-compose.yml
DATA_DIR=$DEPLOY_DIR/data
COOKIES_DIR=$DEPLOY_DIR/cookies

DEFAULT_HOST_PORT=3099
DEFAULT_PORT=3099
DEFAULT_TZ=Europe/Vienna
DEFAULT_COMMAND_PREFIX='$panel'
DEFAULT_YT_DLP_PACKAGE='yt-dlp[default]'
DEFAULT_YT_DLP_FORMAT='bestvideo[vcodec!=none]+bestaudio[acodec!=none]/best[vcodec!=none][acodec!=none]/best*[vcodec!=none][acodec!=none]/best'
DEFAULT_SCHEDULER_POLL_MS=1000
DEFAULT_STARTUP_TIMEOUT_MS=15000

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf 'Missing required command: %s\n' "$1" >&2
    exit 1
  fi
}

require_docker_compose() {
  require_command docker
  if ! docker compose version >/dev/null 2>&1; then
    printf 'docker compose is required.\n' >&2
    exit 1
  fi
}

read_env_value() {
  key=$1

  if [ ! -f "$ENV_FILE" ]; then
    return 0
  fi

  line=$(grep -m1 "^${key}=" "$ENV_FILE" 2>/dev/null || true)
  if [ -n "$line" ]; then
    printf '%s\n' "${line#*=}"
  fi
}

current_or_default() {
  key=$1
  fallback=$2
  value=$(read_env_value "$key")

  if [ -n "$value" ]; then
    printf '%s\n' "$value"
  else
    printf '%s\n' "$fallback"
  fi
}

prompt_with_default() {
  label=$1
  default=$2

  if [ -n "$default" ]; then
    printf '%s [%s]: ' "$label" "$default" >&2
  else
    printf '%s: ' "$label" >&2
  fi
  IFS= read -r answer || true

  if [ -n "$answer" ]; then
    printf '%s\n' "$answer"
  else
    printf '%s\n' "$default"
  fi
}

prompt_secret() {
  label=$1
  current=$2

  if [ -n "$current" ]; then
    printf '%s [leave blank to keep current]: ' "$label" >&2
  else
    printf '%s: ' "$label" >&2
  fi

  if command -v stty >/dev/null 2>&1 && [ -t 0 ]; then
    stty -echo
    trap 'stty echo >/dev/null 2>&1 || true' EXIT INT TERM
  fi

  IFS= read -r answer || true

  if command -v stty >/dev/null 2>&1 && [ -t 0 ]; then
    stty echo
    trap - EXIT INT TERM
  fi

  printf '\n' >&2

  if [ -n "$answer" ]; then
    printf '%s\n' "$answer"
  else
    printf '%s\n' "$current"
  fi
}

prompt_yes_no() {
  label=$1
  default=$2

  if [ "$default" = "y" ]; then
    suffix=Y/n
  else
    suffix=y/N
  fi

  while :; do
    printf '%s [%s]: ' "$label" "$suffix" >&2
    IFS= read -r answer || true
    answer=$(printf '%s' "$answer" | tr '[:upper:]' '[:lower:]')

    if [ -z "$answer" ]; then
      answer=$default
    fi

    case "$answer" in
      y|yes)
        printf '1\n'
        return 0
        ;;
      n|no)
        printf '0\n'
        return 0
        ;;
    esac

    printf 'Please answer y or n.\n' >&2
  done
}

assert_positive_integer() {
  name=$1
  value=$2

  case "$value" in
    ''|*[!0-9]*)
      printf '%s must be a positive integer.\n' "$name" >&2
      exit 1
      ;;
    0)
      printf '%s must be greater than 0.\n' "$name" >&2
      exit 1
      ;;
  esac
}

ensure_layout() {
  mkdir -p "$DATA_DIR"
  mkdir -p "$COOKIES_DIR"
  if [ ! -f "$DATA_DIR/.gitkeep" ]; then
    : > "$DATA_DIR/.gitkeep"
  fi
  if [ ! -f "$COOKIES_DIR/.gitkeep" ]; then
    : > "$COOKIES_DIR/.gitkeep"
  fi
}

write_env_file() {
  discord_token=$1
  host_port=$2
  port=$3
  timezone=$4
  commands_enabled=$5
  command_prefix=$6
  allowed_author_ids=$7
  yt_dlp_cookies_from_browser=$8
  yt_dlp_cookies_file=$9
  yt_dlp_package=${10}
  yt_dlp_format=${11}
  scheduler_poll_ms=${12}
  startup_timeout_ms=${13}

  ensure_layout
  umask 077

  {
    printf '# Generated by install.sh / config.sh\n'
    printf 'DISCORD_TOKEN=%s\n' "$discord_token"
    printf 'HOST_PORT=%s\n' "$host_port"
    printf 'PORT=%s\n' "$port"
    printf 'TZ=%s\n' "$timezone"
    printf 'DATA_FILE=/app/examples/control-panel/data/control-panel-state.json\n'
    printf 'DISCORD_COMMANDS_ENABLED=%s\n' "$commands_enabled"
    printf 'COMMAND_PREFIX=%s\n' "$command_prefix"
    printf 'COMMAND_ALLOWED_AUTHOR_IDS=%s\n' "$allowed_author_ids"
    printf 'YT_DLP_COOKIES_FROM_BROWSER=%s\n' "$yt_dlp_cookies_from_browser"
    printf 'YT_DLP_COOKIES_FILE=%s\n' "$yt_dlp_cookies_file"
    printf 'YT_DLP_PACKAGE=%s\n' "$yt_dlp_package"
    printf 'YT_DLP_FORMAT=%s\n' "$yt_dlp_format"
    printf 'SCHEDULER_POLL_MS=%s\n' "$scheduler_poll_ms"
    printf 'STARTUP_TIMEOUT_MS=%s\n' "$startup_timeout_ms"
  } > "$ENV_FILE"
}

configure_env() {
  current_token=$(read_env_value DISCORD_TOKEN)
  current_host_port=$(current_or_default HOST_PORT "$DEFAULT_HOST_PORT")
  current_port=$(current_or_default PORT "$DEFAULT_PORT")
  current_timezone=$(current_or_default TZ "$DEFAULT_TZ")
  current_prefix=$(current_or_default COMMAND_PREFIX "$DEFAULT_COMMAND_PREFIX")
  current_allowed=$(current_or_default COMMAND_ALLOWED_AUTHOR_IDS "")
  current_cookies_from_browser=$(current_or_default YT_DLP_COOKIES_FROM_BROWSER "")
  current_cookies_file=$(current_or_default YT_DLP_COOKIES_FILE "")
  current_ytdlp_package=$(current_or_default YT_DLP_PACKAGE "$DEFAULT_YT_DLP_PACKAGE")
  current_format=$(current_or_default YT_DLP_FORMAT "$DEFAULT_YT_DLP_FORMAT")
  current_poll=$(current_or_default SCHEDULER_POLL_MS "$DEFAULT_SCHEDULER_POLL_MS")
  current_timeout=$(current_or_default STARTUP_TIMEOUT_MS "$DEFAULT_STARTUP_TIMEOUT_MS")
  current_commands=$(read_env_value DISCORD_COMMANDS_ENABLED)

  if [ "$current_commands" = "0" ]; then
    command_default=n
  else
    command_default=y
  fi

  while :; do
    discord_token=$(prompt_secret "Discord user token" "$current_token")
    if [ -n "$discord_token" ]; then
      break
    fi
    printf 'Discord user token is required.\n' >&2
  done

  host_port=$(prompt_with_default "Web panel host port" "$current_host_port")
  port=$(prompt_with_default "Container port" "$current_port")
  timezone=$(prompt_with_default "Timezone" "$current_timezone")
  commands_enabled=$(prompt_yes_no "Enable Discord chat commands" "$command_default")
  command_prefix=$(prompt_with_default "Discord command prefix" "$current_prefix")
  allowed_author_ids=$(prompt_with_default "Allowed Discord author IDs (comma separated, blank = self only)" "$current_allowed")
  yt_dlp_cookies_from_browser=$(prompt_with_default "yt-dlp browser cookies (optional, e.g. edge or chrome:Default)" "$current_cookies_from_browser")
  yt_dlp_cookies_file=$(prompt_with_default "yt-dlp cookies file (optional, e.g. /app/examples/control-panel/cookies/yt-dlp-cookies.txt)" "$current_cookies_file")
  yt_dlp_package=$(prompt_with_default "yt-dlp package spec for Docker builds" "$current_ytdlp_package")
  yt_dlp_format=$(prompt_with_default "yt-dlp format selector" "$current_format")
  scheduler_poll_ms=$(prompt_with_default "Scheduler poll interval in ms" "$current_poll")
  startup_timeout_ms=$(prompt_with_default "Stream startup timeout in ms" "$current_timeout")

  assert_positive_integer "Web panel host port" "$host_port"
  assert_positive_integer "Container port" "$port"
  assert_positive_integer "Scheduler poll interval" "$scheduler_poll_ms"
  assert_positive_integer "Stream startup timeout" "$startup_timeout_ms"

  write_env_file \
    "$discord_token" \
    "$host_port" \
    "$port" \
    "$timezone" \
    "$commands_enabled" \
    "$command_prefix" \
    "$allowed_author_ids" \
    "$yt_dlp_cookies_from_browser" \
    "$yt_dlp_cookies_file" \
    "$yt_dlp_package" \
    "$yt_dlp_format" \
    "$scheduler_poll_ms" \
    "$startup_timeout_ms"
}

compose() {
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" "$@"
}
